# **Step 1: Setup SQLite**

In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect("agency.db")
cursor = conn.cursor()

# **Step 2: Create Proper Relational Table**

In [3]:
cursor.execute("""
CREATE TABLE clients (
    client_id INTEGER PRIMARY KEY,
    client_name TEXT,
    industry TEXT,
    city TEXT
)
""")

cursor.execute("""
CREATE TABLE projects (
    project_id INTEGER PRIMARY KEY,
    client_id INTEGER,
    project_type TEXT,
    project_cost INTEGER,
    start_date TEXT,
    payment_status TEXT,
    FOREIGN KEY (client_id) REFERENCES clients(client_id)
)
""")

conn.commit()

# **Step 3: Insert More Realistic Data**

In [4]:
clients_data = [
    (1, "KOP Studios", "Media", "Kolhapur"),
    (2, "Aishwarya Design", "Design", "Pune"),
    (3, "Tech Startup", "Technology", "Bangalore"),
    (4, "Fitness Studio", "Fitness", "Mumbai"),
    (5, "Retail Brand", "Retail", "Pune")
]

projects_data = [
    (1, 1, "Portfolio", 120000, "2023-01-10", "Paid"),
    (2, 2, "Branding", 85000, "2023-02-15", "Pending"),
    (3, 3, "E-commerce", 200000, "2023-03-05", "Paid"),
    (4, 4, "Business Website", 95000, "2023-04-12", "Paid"),
    (5, 5, "E-commerce", 175000, "2023-05-18", "Pending"),
    (6, 1, "Maintenance", 45000, "2023-06-10", "Paid"),
    (7, 3, "Branding", 110000, "2023-07-20", "Paid")
]

cursor.executemany("INSERT INTO clients VALUES (?, ?, ?, ?)", clients_data)
cursor.executemany("INSERT INTO projects VALUES (?, ?, ?, ?, ?, ?)", projects_data)

conn.commit()

# **Step 4: Run Professional SQL Queries**

In [5]:
pd.read_sql("SELECT SUM(project_cost) as total_revenue FROM projects", conn)

   total_revenue
0         830000

Revenue by City (JOIN)

In [6]:
query = """
SELECT c.city, SUM(p.project_cost) as total_revenue
FROM clients c
JOIN projects p ON c.client_id = p.client_id
GROUP BY c.city
ORDER BY total_revenue DESC
"""
pd.read_sql(query, conn)

        city  total_revenue
0  Bangalore         310000
1       Pune         260000
2   Kolhapur         165000
3     Mumbai          95000

Revenue by Industry

In [7]:
query = """
SELECT c.industry, COUNT(p.project_id) as total_projects,
SUM(p.project_cost) as total_revenue
FROM clients c
JOIN projects p ON c.client_id = p.client_id
GROUP BY c.industry
ORDER BY total_revenue DESC
"""
pd.read_sql(query, conn)

     industry  total_projects  total_revenue
0  Technology               2         310000
1      Retail               1         175000
2       Media               2         165000
3     Fitness               1          95000
4      Design               1          85000

Advanced: Ranking Cities

In [8]:
query = """
SELECT city, total_revenue,
RANK() OVER (ORDER BY total_revenue DESC) as revenue_rank
FROM (
    SELECT c.city, SUM(p.project_cost) as total_revenue
    FROM clients c
    JOIN projects p ON c.client_id = p.client_id
    GROUP BY c.city
)
"""
pd.read_sql(query, conn)

        city  total_revenue  revenue_rank
0  Bangalore         310000             1
1       Pune         260000             2
2   Kolhapur         165000             3
3     Mumbai          95000             4

# **Step 5: Download the Database File**

In [9]:
from google.colab import files
files.download("agency.db")